### PR TITLE
Support for installation by pip

### PR DESCRIPTION
**Pull request by wil3**
Easily install as a module to allow other programs to use this API. First step to be able to upload to PyPI.

### CODE REVIEW

**Comment by wil3** [comment]
@alduxvm , We may have to revert this PR. The MSP over TCP modifications I was adding in seem to have been included and should be a separate PR. I havnt tested over serial with these changes.

**Comment by alduxvm** [comment]
all revert? or until "made protocol agnostic..."?

**Comment by wil3** [comment]
This PR should be for all commits on Jun 22. I believe I need to separate them into two separate branches. We cant exclude commits from this PR correct?

**Comment by alduxvm** [comment]
Ok, I'll revert all and will hold... thanks for your help in making this more easily accessible for everyone! :D

**Comment by wil3** [comment]
My pleasure, glad I could help. Were doing SITL stuff in my lab with cleanflight/betaflight so this library will be real helpful doing tests.

Doesnt seem the revert went through. Looks like I'm able to do it, OK if I do it?

I put the pip changes in a separate branch so I'm ready to resubmit a new PR after this gets reverted.

**Comment by alduxvm** [comment]
yes please, you revert it... I'm happy that this library is growing and now I think you're the second or third person to do a pull request! :)

**Comment by wil3** [comment]
Ah looks like we can't automatically revert because of the commit that was made right afterward the PR merge. Reset master branch?

**Comment by alduxvm** [comment]
ok, after several tests, I was able to restore the repo to before you did changes, let me know when you're ready to do the PR and I'll make it. I don't have any naze32 to test, but will probably get one and do tests so we can port it to pip and do more stuff... cheers!

**Comment by wil3** [comment]
I think what needed to happen on your side ( which I did on mine) was reset the master to the commit before the PR. Since that didnt happen and the original commits are still in the history I can no longer make a PR because git doesnt think anything has changed. If no feature commits have been made afterward this can still be done with 
`git reset --hard a4b1c64a8c9b85563bc5119a72dd8121967ff873`
on the master branch which will roll back to this commit, https://github.com/alduxvm/pyMultiWii/commit/a4b1c64a8c9b85563bc5119a72dd8121967ff873
 
Then force an update to the remote. If this isnt an option let me know and I'll just reclone the repo and start again.

**Comment by alduxvm** [comment]
I think I already did that... can you check??

**Pull request merged**
